language: python
sudo: false
os:
  - linux
dist: xenial
python:
  - 3.5
  - 3.6
  - 3.7
env:
  - NUMPY=1.14
  - NUMPY=1.15
  - NUMPY=1.16
matrix:
  exclude:
    - python: 3.7
      env: NUMPY=1.14
install:
  - pip install -r requirements.txt
  - pip install numpy==$NUMPY
  - python setup.py install
script:
  - pytest tests
  # - sphinx-build docs/source docs/build #-W
after_success:
  - codecov